version: '2'
services:
    debidadefensa-app:
        image: debidadefensa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://debidadefensa-postgresql:5432/debidadefensa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=debidadefensa-elasticsearch:9300
        ports:
            - 8080:8080
    debidadefensa-postgresql:
        extends:
            file: postgresql.yml
            service: debidadefensa-postgresql
    debidadefensa-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: debidadefensa-elasticsearch
