export * from './documentos.model';
export * from './documentos-popup.service';
export * from './documentos.service';
export * from './documentos-dialog.component';
export * from './documentos-delete-dialog.component';
export * from './documentos-pdfviewer-dialog.component';
export * from './documentos-detail.component';
export * from './documentos.component';
export * from './documentos.route';
